### ISSUE TITLE
VDFS seg faults

### ISSUE THREAD

**Issue by davidgiven** [stardot/b-em#28] opened 2017-10-07 09:39 UTC
If I modify a directory which the emulated platform has open, I frequently get a null pointer access in `scan_dir()`. I don't know _why_ because I don't know the logic, unfortunately --- it appears that there are NULL entries in `dir->cat_tab`, which causes this loop to fail:

```
while (ptr < end) {
    ent = *ptr++;
    ent->attribs |= ATTR_DELETED;
}
```

Adding a simple `if ent {}` around the obvious line stops the immediate crash, but is probably the wrong solution.

**Comment by SteveFosdick** [comment] 2017-10-07 20:20
OK, in looking into this I have found another bug which causes a crash if you delete all the files in a directory the BBC has open and then attempt *. on the BBC.  The solution for that is in scan_dir and is to add a line to the case that handles no files found:
```
            if (count == 0) {
                dir->cat_size = 0;
                dir->scan_seq = scan_seq;
                dir->scan_mtime = stb.st_mtime;
                return 0;
            }
```
but I haven't been able to reproduce the issue of the NULL pointer.  I have added a warning, as the else of the if you mentioned, and another warning for one possible cause but I can't get them to trigger.

So far I have just tried adding and removing files from the host, issuing *. and *TYPE on the files concerned.  I'll have another look when I have more time but if there is any specific sequence that reliably triggers the bug that would obviously be really useful to know.

**Comment by davidgiven** [comment] 2017-10-07 20:37
It was 100% reproducable for me... but I was doing compiler development with a huge directory with lots of churn, so that doesn't help you much.

Incidentally, possibly related:

```
BEM_VDFS_ROOT=/this/directory/does/not/exist ./b-em
```

...then doing `*.` causes (for me) an endless spew of blank filenames.

**Comment by SteveFosdick** [comment] 2017-10-08 18:47
Ok,.I have created a new branch, issue28, in the Stardot Github repository for b-em which has some fixes including the invalid root dir issue, an error message issue and the "delete all files from the host" case.  It also includes a warning message for when the null pointer is encountered.

I have still had no luck reproducing the null pointer issue, though.

**Comment by SteveFosdick** [comment] 2017-11-14 23:51
I accidentally ran into this myself and the key to reproducing it seemed to be to create a new file from inside the emulated BBC.  After re-writing some bits of VDFS to support the delete and rename operations it has not happened again.  It would be worth re-testing on the issue28 branch which contains all the recent changes to VDFS including delete and rename.

**Comment by SteveFosdick** [comment] 2017-12-15 00:40
It's been a month with no further reports so I will close this.  Feel free to reopen if that turns out to be too optimistic.

**Closed as completed by SteveFosdick** 2017-12-15 00:40 UTC
Labels: bug
