### ISSUE TITLE
hdfmt when built for Windows , fails to intialise an image with an FS map per specfication...

### ISSUE THREAD

**Issue by afarlie** [stardot/b-em#70] opened 2018-08-16 18:34 UTC
In a special built version of hdfmt, a dsc, dat file combination generated or modified by the tools was not recognised by the emulator,  the BBC style error generated was "Bad FS Map" suggesting that it's view of what should be seen on the image differs from what is physically present in the image file concerned.

**Comment by afarlie** [comment] 2018-08-17 07:28
Resolved in trunk?

**Comment by SteveFosdick** [comment] 2018-08-27 19:57
This was caused by hdfmt not specifying binary mode when opening the file.  It is fixed in commit 2bb541d51f6ca9ef2d8ed69dead28d30910f32e8 which is in the current master,

Also fixed is failure to build this program by default on Windows.

**Closed as completed by SteveFosdick** 2018-08-27 19:57 UTC
