### ISSUE TITLE
Remap keys doesn't seem to work on windows 7

### ISSUE THREAD

**Issue by richard-broadhurst** [stardot/b-em#135] opened 2021-02-08 17:33 UTC
I'm on Windows7 and by default @ (SHIFT ') does not produce * (SHIFT :).
I do settings|keyboard|remap and click on : and then press the ' key and OK.
' still produces _, not : and SHIFT ' still produces @, not *.
PS when I press ', it says that it is currently assigned to Alt-4.

**Comment by richard-broadhurst** [comment] 2021-02-08 17:36
Experimenting, I tried to map ' to End and it crashed b-em.
I didn't actually want that mapping.

**Comment by SteveFosdick** [comment] 2021-02-08 18:01
Ok I can reproduce the crash.  It seems to be a bit random.  I suspect maybe the issue is caused by the keymapper updating a data structure the main window is also using.

**Comment by SteveFosdick** [comment] 2021-02-08 18:56
Ok, I think I have this fixed now - it was seeing what should have been BBC keycodes as actions (i.e. things that control the emulator itself).  That would have accounted for the crash (outside of an array bounds) and the non-working mapping.

Fix is in: https://github.com/stardot/b-em/tree/sf/keymapfix

**Comment by SteveFosdick** [comment] 2021-03-06 22:39
The fix for this is merged.

**Closed as completed by SteveFosdick** 2021-03-06 22:39 UTC
