### ISSUE TITLE
Disc created using "New disc" gets inverted write protect in GUI

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#96] opened 2019-12-07 23:55 UTC
Hi,

I hope I'm not going crazy here, please let me know if you can't easily reproduce this and I'll investigate further.

- Start with b-em set to Master 128 mode, ensure "Default write protect" is ticked and eject all the virtual discs.
- Close b-em
- Restart b-em
- Choose Disc->New disc :0/2->Acorn DFS single-sided 40T and create a new test.ssd image
- Observe on the Disc menu that drive 0/2 is not shown as write protected
- *SAVE Z 900 910 fails with "Disc read only"
- Toggle the write protect on the Disc menu for drive 0/2, so it *is* ticked
- *SAVE Z 900 910 now works
- Close b-em
- Restart b-em
- Observe on the Disc menu that drive 0/2 is not shown as write protected
- *SAVE Q 900 910 fails with "Disc read only"
- Toggle the write protect on the Disc menu for drive 0/2, so it *is* ticked
- *SAVE Q 900 910 now works

This is on Ubuntu 18.04.3 LTS, in case it matters, built from current master (aba1558ecf7b93c8352ea8c25097978f7ef70551).

It looks to me as though the New disc option does something wrong with setting the write protect status, and (more oddly?) this oddness persists across the emulator being closed and re-opened.

Let me know if you need any more information, of course!

Cheers.

Steve

**Comment by SteveFosdick** [comment] 2019-12-09 21:57
Yes, I can reproduce this.  I think the problem is a little wider than this bug report, though.  It seems that the only place the tick in the disc menu and the internal read-only flag for a disc are synchronised are when an existing disc is loaded from the menu.  When the disc is created from the menu or is automatically re-loaded when b-em starts the synchronisation doesn't take place.

**Comment by SteveFosdick** [comment] 2019-12-09 22:31
Try the latest master which should have a fix for this.

**Comment by ZornsLemma** [comment] 2019-12-10 00:28
Yes, latest master fixes this issue for me, thanks.

Just a thought: although it's completely logical and consistent the way it behaves now, maybe "default write protect" shouldn't apply to discs created via the "new disc" menu? I would imagine anyone creating a new blank image is going to want to modify it immediately.

**Comment by SteveFosdick** [comment] 2019-12-19 12:27
I had wondered about that too.  Does one do what the user instructs of what they probably want?  I'll have a look and see how easy it would be to do that.

**Comment by SteveFosdick** [comment] 2019-12-27 18:13
I have create a new branch for this issue and pushed another couple of fixes to it.  One ignores the write protect for new discs as you suggest, the other sets the tick on the menu correctly when the image file is read-only.

**Comment by SteveFosdick** [comment] 2020-07-17 00:51
The fixes for this is in the current master - new discs are always r/w.

**Closed as completed by SteveFosdick** 2020-07-17 00:51 UTC
