### ISSUE TITLE
Show state of LEDs

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#84] opened 2019-05-21 23:41 UTC
I've been playing around with showing the state of the various LEDs at the bottom of the emulator window:
- cassette motor
- caps lock
- shift lock
- drive 0
- drive 1
- VDFS pseudo-drive (so you can see when VDFS is 'doing stuff')

It's still a bit of a mess but I think there's some potential there. Is this something which would be considered for merging if I can get it working nicely? I'd hide this behind an option on the menus so you don't have to have the LEDs if you don't like them.

**Comment by SteveFosdick** [comment] 2019-05-22 00:56
I think some people will appreciate this.  I might even find it useful myself as the host caps lock key isn't a good indicator of what will happen when I start typing.

With the floppy drives there is an obvious cue for the LED to go on/off as there is a motor on or similar signal.  There are also hard discs not on your list, both SCSI and IDE and these don't have a motor signal so it may be a case of turning the light on when a command is issued and then leaving it on until a short time after the last command has completed.  Likewise VDFS is much too fast to only have the light on when something is actually happening so again it may need a timer.

If that's all a bit complicated I'd start with the keyboard state, cassette motor and the two floppies and then see if you still have enthusiasm to continue.

**Comment by ZornsLemma** [comment] 2019-05-22 11:30
Thanks, I had forgotten about hard drives - I'll make a note to add them. My prototype already has a timer and that's what I use for VDFS; activity turns the LED on for 10 frames then it goes off if nothing else has caused it turn back on. So I should be able to use that for hard drives without too much trouble.

(The code is an enormous hack and needs lots of things reworking, but FWIW it can be seen at https://github.com/ZornsLemma/b-em/tree/leds)

**Comment by SteveFosdick** [comment] 2019-05-22 18:49
I did try your prototype and I like it.

You mention in the code that the LEDs don't have their own space - if the border is not very wide they can be drawn on top of the display from the BBC itself.  Some other emulators handle this by making them transient, only appearing when there has been recent change and then disappearing again, maybe even with a fancy fade out.  The other option is to re-size the window to make space which takes you into the territory of Issue #79, the function video_set_window_size in vidalleg.c and the associated constants.

SCSI and IDE are mutually exclusive, I think because the interfaces occupy the same space in the memory map.  ADFS only supports 4 hard discs so this is how many the SCSI emulation supports.  I think IDE supports two, just like a PC IDE interface.

The light for VDFS behaves rather differently than with real discs because it only lights for file access and not for metadata access.  There are several other places that could light the LED in VDFS including loading files into memory for the SWRAM commands (exec_swr_fs) and the fallback implementation of OSWORD 7F for the case that VDFS happens to be the current filing system when sector load/save is used.  Before tackling any of that, though there are quite a few changes between the version of VDFS in the master you forked from and the current one so there is a high risk of merge conflict.  The more recent VDFS avoids making so mucg use of getc/putc and there are some functions that may be easier to hook than OSFILE etc. i.e. write_bytes, read_file_io, and read_file_tube.  Hooking these three should get the majority of cases and then just some odd ones to do.

**Comment by ZornsLemma** [comment] 2019-05-23 23:16
Thanks for taking a look! I had contemplated doing a fancy fade out option, but what put me off (assuming I could make it work technically) was the fact that the caps lock LED is "normally" on. I haven't definitely ruled out something like this, the code is very much a work in progress and you may or may not have noticed I struggled to find the right place to call led_init(). I'd like to call it very early on along with the other foo_init() functions, but if I do that "something" is missing and drawing into led_bitmap in led_init() has no effect. I'm sure I've just overlooked some Allegro call, but I temporarily hacked it so I just call led_init() ridiculously late at a point where it works.

Do you think we'd want 2 or 4 hard drive lights, one for each emulated hard drive? This might be OTT but it is more "realistic". I suppose it's here that the automatically-fading-out style would help.

I semi-deliberately didn't light the VDFS LED for read operations on metadata (I'd hope that write operations on metadata do light it) because I was working on a mental model that these would be cached in RAM (doesn't ADFS behave like this? Not sure, I could easily be wrong). I'm not wedded to this model and it would be fine with me to just light the VDFS LED for all read/write operations. I'm quite happy to throw away my modified vdfs.c and redo the changes on a newer version later on; especially if it's just those three functions you mention and a few other odd ones it's not a big deal.

I did/do intend to look at resizing the window to make space but I seemed to keep running up against a few bugs in the display code; I need to make sure I've got the latest version and test without my changes present and raise some issues on here if I can still reproduce them. I'd like to make sure everything's working before I go in and fiddle and maybe cause more breakage...

**Comment by SteveFosdick** [comment] 2019-09-20 10:47
Steve this was some promising work.  Can we pick it up again?

**Comment by ZornsLemma** [comment] 2019-10-27 01:55
Hi, sorry for ignoring your last comment for a month! I've been a bit slack about checking up on the folder my github notifications get filtered into so only just saw this when I happened to check the issues page to see what had been going on. (Do feel free to just e-mail me if I seem to be ignoring you in the future!)

I went visiting family for a couple of weeks just after we were last talking about this and didn't have a machine capable of running b-em so couldn't work on it then, and after being forced to take a break I sort of got distracted. So I haven't done any more work on this, but I will see if I can take a look over the next few days and pick it up again.

**Comment by ZornsLemma** [comment] 2019-10-27 02:00
Incidentally, is there any particular branch you think it would be best for me to work from (I'll start by merging my existing branch over there)? master?

**Comment by SteveFosdick** [comment] 2019-10-28 18:13
Don't worry about the month - I find I have times when I have some enthusiasm for doing something to B-Em and times when I have other things on.

The situation with branches is a bit complicated at the moment but master should be a good base for a new branch.

On the question of hard disc lights I don't have a strong opinion on how many.  I suspect most people who configure a hard disc probably only use one so you could get away with only one light and for the case where someone has more than one, light it when any of them is accessed.  On the other hand if you have an extra strip along the bottom where the lights are permanently displayed then you have plenty of width so it wouldn't matter if there were four.

On the question of the light, VDFS and metadata that's an interesting point about caching - VDFS does indeed do some metadata caching in particular it tries to avoid having to open/parse all the .inf files in a directory every time the directory is searched for a name.  That also allows it to make sure the name as seen on the BBC micro is unique and, where it has had to alter one of the names to make it unique, the mapping remains stable.  So the way you had it is fine.

It does make me think what the purpose of a drive access light is.  At the most basic level I think it is there to explain why something is taking a while, i.e. "this operation will not be immediate because I/O is required".  Showing individual devices can also help give you confidence, for example that you are saving your program to the right disc.

If you do get into calculating a bigger window border with the light enabled you will notice there is a "fudge factor" in the calculation.  Without checking the source I can't remember which way round it is but it's there because one of Windows or Linux includes the menu within the dimensions of the window and the other doesn't, i.e. treats the dimensions as those of the content area.

**Comment by ZornsLemma** [comment] 2019-11-05 19:12
Just a quick note to say I'm intermittently working on this! I've created a new leds2 branch off recent master to work on: https://github.com/ZornsLemma/b-em/tree/leds2

There are some new LED menus under the "Video" menu which don't actually control anything yet.

I also have basic support for showing LEDs only when something changes, and fading them out afterwards; right now this is the hard-coded behaviour but ultimately this will be controlled via the menus.

For purposes of fading out the LEDs, the disc/VDFS LEDs are treated specially (they're "transient", in the terminology used internally by the code) and if they're on the LEDs won't ever fade out. The idea here is that it's "interesting" that they're on because they only come on briefly when stuff is happening, unlike (say) the Caps Lock LED. This will also be configurable eventually, but currently it's hard-coded to use this behaviour. (If you do want to play with this, the cassette motor LED is the only currently implemented LED which isn't transient, so you can play with *MOTOR commands to toggle that on and off and note that it being on *doesn't* cause the LEDs to be displayed; only when it changes state do the LEDs appear for a few seconds.)

I haven't done any work on hard drive LEDs, floppy LEDs for the 8271, tweaking the VDFS LED or supporting Caps Lock/Shift Lock LEDs yet; I'd like to get the basic framework sorted before fiddling with these.

If you have any feedback do let me know, but you don't need to take a look at this point - I'll let you know when the code approaches actual completion.

Cheers.

**Comment by SteveFosdick** [comment] 2019-11-07 23:01
I just some initial testing and managed to get the VDFS light stuck on.  I'll see if I can work out what is going on.  In the mean time I had a peak the 1770.  Looking at this:
```
void wd1770_spinup()
{
    wd1770.status |= 0x80;
    led_update((curdrive == 0) ? LED_DRIVE_0 : LED_DRIVE_1, true, 0 /* SFTODO LED_DRIVE_TICKS */);
    if (!motoron) {
        motoron = 1;
        motorspin = 0;
        ddnoise_spinup();
    }
}
```
I am thinking the LED should come on at the same time as the drive noise starts so I'd put the hook there:
```
void wd1770_spinup()
{
    wd1770.status |= 0x80;
    if (!motoron) {
        motoron = 1;
        motorspin = 0;
        led_update((curdrive == 0) ? LED_DRIVE_0 : LED_DRIVE_1, true, 0 /* SFTODO LED_DRIVE_TICKS */);
        ddnoise_spinup();
    }
}
```
Although this may not be critical as, presumably if you turn on an LED which is already on then it will not change whereas the noise would re-start.  Likewise when DFS switches drives, as long as it is only DFS messing with the driver select latch no problem, but in theory at the moment someone could write to that latch and it would put an LED on.  If that were also protected by checking the motor is on it would be immune to that, i.e.
```
static void write_ctrl_master(uint8_t val)
{
    log_debug("wd1770: write master-style ctrl %02X", val);
    if (val & 0x04)
        wd1770_reset();
    wd1770.ctrl = val;
    curdrive = (val & 2) ? 1 : 0;
    if (motoron) {
        // SFTODO: IF THIS WORKS NEED SAME LOGIC FOR OTHER CONTROLLERS...
        led_update((curdrive == 0) ? LED_DRIVE_0 : LED_DRIVE_1, true, 0 /* SFTODO LED_DRIVE_TICKS */);
        led_update((curdrive == 0) ? LED_DRIVE_1 : LED_DRIVE_0, false, 0 /* SFTODO LED_DRIVE_TICKS */);
    }
    wd1770.curside =  (wd1770.ctrl & 0x10) ? 1 : 0;
    wd1770.density = !(wd1770.ctrl & 0x20);
}

```

**Comment by ZornsLemma** [comment] 2019-11-08 02:24
Thanks, I will take a look at making the changes you suggest re the 1770 - the existing code is all the result of my initial experiments to get *something* working and I probably didn't choose the best way of doing things.

Please don't spend too much time looking into the VDFS LED sticking on issue - this could just be a bug in the rather hacky code rather than anything deep. My development process for stuff like this is to kludge things in to prove I can make them mostly work, then gradually polish things up - and this code has had no polishing at all as I'm still implementing bits of functionality. Obviously if you find the bug that's great but I'd hate for you to waste a lot of time on it at this point.

**Comment by SteveFosdick** [comment] 2019-11-10 00:18
I didn't spend long looking for what was going on with VDFS but a quick check found the hooks into VDFS only turn the light on so I assume it is meant to be turned off by counting timed events.

If you need to be called regularly after some period of time has elapses there are basically two ways - the chain of things that get executed from polltime in 6502.c which applies to anything that has to be in tight sync with the CPU and the function main_timer in main.c for things where synchronisation need not be so tight (fine for these LEDs, I would think).  In looking to find that I noticed that function has some ddnoise stuff in it too and it occurred to me that, at least for floppies, the best places to hook for LEDs are probably the same places as ddnoise already has hooks as that starts and stops noises with the drive motor as a real LED would do.

On this comment:

>     // SFTODO THE FOLLOWING LOOP SEEMS TO HAVE NO EFFECT! - I THINK THE MAIN
    // CODE IS NOT DRAWING THE BITMAP UNTIL THE CURSOR MOVES OVER IT, THIS LOOP
    // ITSELF IS PROBABLY FINE

The allegro calls draw to the current bitmap and I don't know what that would be at that time.  It could be the backbuffer or an intermediate bitmap.  Either way it probably won't appear on screen until the next al_flip_display which happens once the frame is fully drawn.

**Comment by ZornsLemma** [comment] 2019-11-10 21:04
It looks like I had simply screwed things up when merging the old 'leds' branch to create the new 'leds2' branch - there was previously a call to led_timer_fired() in main_timer() which had got lost. I hadn't tested VDFS myself after the merge; your hint about main_timer() made it easy to find this problem, so thanks for that. This should (based on a super quick test) fix the VDFS LED issue.

What you say about ddnoise makes sense, but (at least after updating the code to reflect your earlier comments) that seems to be pretty much what we already have for the 1770. I agree looking for the ddnoise calls in the 8271 code will likely be the best way to identify places to add support there. If you're suggesting we could avoid controller-specific code by controlling the LEDs from ddnoise itself, I think the problem is that we need to know which drive is being accessed and ddnoise doesn't have that information (based on a quick look at the code now).

Thanks very much for the comment on that SFTODO comment; at the moment I have completely kludged in the initialisation code, I need to revisit this and what you've said might be the hint I needed to make sense of this.

**Comment by SteveFosdick** [comment] 2020-07-07 21:23
I suddenly remembered this to have I pulled your branch into one of mine on StarDot and made a few minor changes.  The most visible are:

- The Caps lock and Shift lock LEDs now work.
- An LED for the hard disc.  I went with one because, as we already discussed, SCSI and IDE cannot be enabled at the same time and IDE seems to only support one disc anyway.  Yes, SCSI can do four but I wonder how many people have four - we can always change that later, anyway.
- VDFS now lights the LED when it has to scan a host dir rather than just uses it's cache.  That seems to be a bit more natural.
- On the Welcome disc I found in overlay mode the LEDs were putting a black rectangle on top of the white background.  I hadded an alpha channel to the fade out to resolve that.

Other than that I have tweaked a couple of things you marked as TODO.  I also couldn't get the initialisation to work in the proper place.  We could come back to it later.

Let me know what you think: https://github.com/stardot/b-em/tree/sf/leds

**Comment by SteveFosdick** [comment] 2020-07-18 02:04
See this commit which fixed properly the issue worked around by having late initialisation of LEDs.  https://github.com/stardot/b-em/commit/bc1228a600420a02e1e51b49a003cb9d1813c2df

**Comment by ZornsLemma** [comment] 2020-07-19 21:38
Thanks for the mail you sent me about this; apologies for not seeing the above, I've (hopefully) stopped filtering github mails about b-em into a lower priority mailbox so I should see them in future.

It looks like you've really polished this up, thanks a lot for that - I feel a bit guilty for leaving it to you, although you've probably done a better job if it than I could have. I did notice one of your stardot posts the other day had a screenshot which showed the LEDs on!

When I read your e-mail my initial reaction was "no, four hard disc LEDs will look silly". Then I actually compiled the code and it looks pretty good, I like the way the LEDs fit nicely across the emulator window (at least in the 640x512 size I normally use, and which I think is the b-em default). From a practical point of view it does seem like overkill but it's not doing any harm and as I say I think it looks good.

While playing with it just now I found that the fade out effect doesn't seem to be working properly **but** I am visiting family at the moment and so am running b-em under Ubuntu 18.04 as a VirtualBox guest OS (with a Windows host), and I think we've previously established that this can cause problems, so it's probably best not to worry about this. (If you're interested I can try to figure out exactly when it goes wrong and provide more details.) If (which seems unlikely) I experience any problems without VirtualBox being involved I will let you know.

(I'll reply separately about the logical keyboard work.)

**Comment by SteveFosdick** [comment] 2020-07-20 22:45
I tried cross compiling for Windows and then running under Windows under VirtualBox and the fade out works there.  I have put up a binary pre-release: https://github.com/stardot/b-em/releases/tag/ledsyms (for Windows).

**Comment by ZornsLemma** [comment] 2020-07-22 16:22
I've just built 9fa7ad590b7270f92e1a444f7b119c3b71506d8f on my Ubuntu 18.04.4 LTS box and I'm afraid the LED fading seems to be broken for me here too, even without VirtualBox in the mix. This is on an i5-2500K using the built-in graphics.

I have LED location set to "Separate", LED visibility set to "When changed" and Borders "Medium". This is all in the config so it's set straight away on startup, to rule out any glitches caused by changing the LED settings on a running emulator.

Putting some debug output in render_leds(), it looks to me as though the fade-out code is being called but it doesn't have any effect. If I hack the "led_tint = al_map_rgba(i, i, i, i)" line to change the final i to 255, the LEDs *do* fade out, but they periodically flicker on and off (between invisible and fullly visible with no intermediate state) afterwards for no reason - this latter problem looks like the one I noted in the commit message on my commit here: https://github.com/ZornsLemma/b-em/commit/10ed525e1b8beac6906777c92aa206f563c9a83d I'm not saying the cause is the same, but the effect is the same one I (claimed) to have fixed in that commit.

I haven't probed this more deeply at this point, but I thought I should mention it to see if you have any thoughts.

(I will probably be upgrading to Ubuntu 20.04 when the point release comes out in August, so if you think this is likely to be caused by outdated libraries on my machine it may not be worth worrying about.)

**Comment by ZornsLemma** [comment] 2020-07-22 17:03
I probably shouldn't say this simply because it's vague but FWIW: I did try the binary releases you posted above on native Windows 7 running on a (different) machine with an i5-2500 (possibly K, not sure) using the integrated graphics and the LED fading didn't seem to work there either, but I *may* have had the settings wrong or unpacked the zip badly. However, I do wonder if there's something incompatible with i5-2500(K) integrated graphics somehow. Quite possibly a total red herring...

[I don't have access to that Windows 7 machine right now, but I will do again in a few weeks.]

**Comment by SteveFosdick** [comment] 2020-07-22 19:50
I can reproduce this - the problem is apparent on Linux with the LEDs set to separate.  I think I probably introduced this bug when I used alpha blending.  The idea behind that was that when the LEDs were on top of some content from the BBC video display they would fade by become more transparent so the other content started to be revealed.  Without doing that the LEDs would fade to a black cutout which looked very odd.

But, I think, when the LEDs are in their own space they are being alpha blended with the image of themselves from the previous frame, not pure black, so that's why the fade does not happen.  So I think the answer is to use alpha blending for the overlaid setting and and an opaque fade for the separate setting.  I'll code that up and try it.

**Comment by ZornsLemma** [comment] 2020-07-22 19:59
Thanks, that makes sense. I'm not sure I'd have worked out that the LEDs could alpha blend with an older version of themselves on my own - but once you put the idea in front of me, I can sort of see how that would happen. This modern graphics stuff is a bit mind-bending sometimes...

**Comment by SteveFosdick** [comment] 2020-07-22 20:58
Hopefully this is fixed now.  I have also fixed the lights for IDE - I somehow had the idea that only had one disc but it can support two (just like in a PC)

**Comment by ZornsLemma** [comment] 2020-07-22 21:15
Thanks, that was quick! I've given this a quick test and the fading seems to work - I'll keep using this build for the next few days and see how I get on. I like the new enum constants too - to be honest I would have done that from the start, but it seemed to be a more b-em-ish style to just use numeric constants and I was perhaps foolishly consistent.

I'm a bit embarrassed to ask, but what is the difference between visibility options "When changed" and "When changed or transient"? I can't seem to see any. Looking at the code on my leds2 branch, I *think* the original intention here was that "when changed" didn't treat the transient LEDs differently - so if (for example) you did "*VERIFY 0", the LEDs would appear briefly when the disc 0 LED came on, then fade out, then appear briefly when the disc 0 LED went off before fading out again. Much as happens if you toggle CAPS LOCK slowly. Whereas in the "*VERIFY 0" case, "when changed or transient" would keep them on during that operation, because the disc LED was flagged as transient. I could be wrong about this, it was a while back now.

**Comment by ZornsLemma** [comment] 2020-07-22 21:22
A totally random thought: it's mildly annoying changing the Caps Lock state of the emulated machine via the host Caps Lock key, because it changes the host setting as well. (Admittedly, judicious use of Shift+Caps Lock can help here because it's "non-toggling" on the emulated machine, so you can toggle the host independently then maybe do a final Caps Lock press to flip both.) If clicking on the Caps Lock LED faked a Caps Lock keypress on the emulated machine, it would be possible to make the change directly without affecting the host. I don't know if this would be easy or not, and it may not be a good idea, but I thought I'd mention it.

**Comment by SteveFosdick** [comment] 2020-07-23 17:06
It's possible, of course.  It would be easier with the LEDs separate.  When overlapped we'd also need to test whether the LEDs are visible to decide whether to pass the mouse click through to AMX mouse emulation.

Another possibility that may be easier is to just remap the keyboard so the key the guest sees as caps lock is not the host caps lock key.

**Comment by SteveFosdick** [comment] 2020-07-23 21:33
Going back to the "when changed" setting, I think there was a bug and "when changed" was being treated the same as "when changed or transient".  I have pushed a commit that I think fixes it.

The fade out is fast enough you can see this even when running *. on a floppy disc.  When in "when changed" mode the LEDs appear when the drive light lights then fade out.  Later, when the DFS stops the drive motor and the LED is extinguished the LED panel appears again with the drive light unlit and fades out again.

**Comment by SteveFosdick** [comment] 2020-07-23 21:37
I have also discovered another small anomaly.  When cataloguing a tape the LEDs keep appearing and then fading out again even though the cassette motor LED seems to be staying on.  I suspect the cassette filing system re-writing the motor on/off bit; what I don't know is if it is turning it off momentarily.

**Comment by ZornsLemma** [comment] 2020-07-23 23:52
Thanks, I've updated to the latest version of this branch and the "when changed" feature now seems to be working. I'll keep using this and see how I get on.

Interesting discovery with the cassette motor. I can reproduce this, although I don't suppose that's surprising. I've had a quick poke at the OS1.20 disassembly but I'm not that familiar with it and it's hard for me to see what's going on. The code to control the cassette motor LED looks pretty straightforward so I suspect what it's showing is real.

Another small anomaly in "When changed" mode (which has always been there) is that when the disc LED goes off, the LEDs fade in and the LED is already off, so it's superficially as though they appeared for no reason. Ideally we might have some sort of time delay on the LED updates so they fade in with it still red, then it goes off a fraction of a second later. I am *not* seriously suggesting we implement this, unless you have some clever idea which would make it trivial to do (I haven't). However, if we had this kind of time delay it might also be possible to use it to avoid behaviour like the cassette motor LED blipping for a tiny fraction of a second having a visible effect. As I say, I'm not seriously suggesting this, just throwing the idea out.

**Comment by SteveFosdick** [comment] 2020-07-24 00:06
On the cassette LED front, the OS really is turning off the cassette motor and then, about 120us later, turning it back on again and if you enable the tape noise setting the cassette relay clicks at that point too.

What I am not sure about, is whether the off period is long enough for anyone using a real machine to perceive it as off.  There is a mechanical relay to control the motor and that may not even change during that really short period of time.  The LED is controlled by the same transistor that controls the relay coil so that is capable of blinking but I wonder if persistence of vision means that no-one would notice.  I might have to try this out with a real machine but that means setting it up so I can feed a audio signal into the tape port.

**Comment by ZornsLemma** [comment] 2020-07-24 00:13
I wonder if saving  to tape would do the same thing? I just tried this on b-em and nothing seemed to happen, but I don't think b-em supports writing to tape anyway. This might save you finding a suitable cable, but unless you can see from the OS disassembly it has the same behaviour it won't prove anything really. I suppose if you try saving and you can see a pulsing in the LED that might be good evidence.

**Comment by ZornsLemma** [comment] 2020-07-24 00:15
To state the obvious: one possible solution would be to increase the delay before the LEDs fade out to >120us. :-) Edit: well, not exactly. You'd still see the blip but the fade wouldn't draw attention to it.

**Comment by SteveFosdick** [comment] 2020-07-24 00:21
Steve, the problem is that the LEDs have already faded out because the OS has been busy reading the tape then, when it gets to the end of that file it turns the motor off, which causes the LEDs to re-appear.  Then, moments later, it turns the motor back on again.  So the LEDs only appear once for that off/on sequence but in "when changed" and transient modes ideally they would appear only when the motor is turned on at the start of the operation and again when you hit Escape at the end because you don't think there is any more on the tape, but not in between.

I do have a fix but I want to see how the real hardware responds.

**Comment by ZornsLemma** [comment] 2020-07-24 19:04
I'm afraid I've found another problem with the LEDs. If I run a music playing program - the sort of thing which just issues loads of SOUND commands and lets the OS queue them up - the LEDs flicker (as, if memory serves, they do on real hardware) and that seems to cause problems with the sound playback, it gets noisy/choppy. This may be my slightly under-powered hardware, but I suspect it's not.

Let me know if you need an example and I'll dig something out, but I'm guessing you will have something of the sort lying around - I don't think it's particularly specific to any particular program. As long as it goes via the OS sound routines and therefore fiddles with the LEDs it should demonstrate the problem.

I initially thought this was caused by the fading in and out but it still happens if I set the LEDs to always visible.

**Comment by SteveFosdick** [comment] 2020-07-24 19:58
Yes, please for the example.  I don't have anything to hand.  The music playing program on the welcome disc tape doesn't provoke the flickering, at least not on a Master - I'll try on a BBC B next.

**Comment by SteveFosdick** [comment] 2020-07-24 20:03
On the tape loading I discovered that, on my Master, there is no click from the relay for the very brief moment the cassette relay is off.  Unfortunately the Master does not have a cassette motor LED so I can't see if that flickers.

On the BBC B nothing happens at all - it seems that machine simply does not see any signal from the "tape" so that is probably a fault.

**Comment by ZornsLemma** [comment] 2020-07-24 20:03
No problem, please try the attached - it's just a BASIC program on a zipped ssd
[music.zip](https://github.com/stardot/b-em/files/4974008/music.zip)
.

**Comment by SteveFosdick** [comment] 2020-07-24 20:28
Ok, I can reproduce the issue and it is specific to have LEDs turned on.  It doesn't happen with the master branch and also not with LED location set to none.

BTW, that tune does not seem to play correctly for me if I just run the program again - if I do <Break>, then OLD and RUN it does.

**Comment by SteveFosdick** [comment] 2020-07-24 20:37
Ok, try the commit I have just pushed.  As well as the noticeable flickering it seems the OS was writing the LED value many times in between as well.

**Comment by ZornsLemma** [comment] 2020-07-24 21:10
That works a treat, thanks. Such a simple fix too!

**Comment by ZornsLemma** [comment] 2020-07-24 21:12
It's weird the tune won't play a second time, I coded it up years ago but I might guess it accidentally leaves one of those OS "chord" type effects (SOUND &201,... and similar) hanging, so the first notes on a replay get swallowed up and things get out of sync. That's just a guess though.

**Comment by SteveFosdick** [comment] 2020-07-25 20:08
So from the response I have receive on the forum it looks like we should leave the relay clicking but avoid the LEDs popping up every tape block because normally there would not be any perceptible change,

**Comment by SteveFosdick** [comment] 2020-07-25 20:23
I have pushed a change to stop the spurious LED update.

**Comment by ZornsLemma** [comment] 2020-07-26 11:55
Thanks Steve, that works. I've had a look at the code and it looks good to me, FWIW.

Was it a deliberate decision not to mark the cassette LED as transient? I don't feel very strongly about it, but I would have probably marked it transient, so the LEDs stay on the screen during loading in "when changed or transient" mode, just like a disc LED would.

I infer from the accidental commit to this branch you've got your new keyboard working, so congratulations on that!

**Comment by ZornsLemma** [comment] 2020-07-26 12:00
Sorry, I spoke too soon. With the new version (in Master Turbo mode, at least, though I doubt it makes a difference), when the machine is powered on or BREAK is pressed, the tape relay click sound plays. That didn't happen before, and I don't think this is correct/deliberate.

**Comment by SteveFosdick** [comment] 2020-07-26 14:19
Oops, the 2nd part of that if didn't avoid the case where the motor was already off.  I have pushed that.  I have also change the cassette relay to transient, though I am not sure I had changed it previously.

I think I had two things confused, though.  Some LEDs have a definite on and off event so, for the cassette and floppies, that is the motor signal.  Others light upon some event and go off on a timer.  I think I had it in my mind that the latter were transient but I think what you mean by transient is an LED that shows something happening or some resource busy that will, in time, go off again, i.e. everything except the keyboard LEDs which would remain on for a whole session.

Yes, the new keyboard is working, and in B-Em too; it's easily the best feel of any keyboard I have had, though I am still getting used to the layout differences.  But that commit is independent of the logical keyboard work and relies on me having installed a patched version of Allegro, which is why I didn't intend pushing to something that will hopefully merge with main.

**Comment by ZornsLemma** [comment] 2020-07-26 17:01
Thanks, that works well.

Yes, I was using "transient" to mean "this LED is not normally on all the time". It's perhaps not the best term since you could fairly describe an LED which goes off within a fixed time as transient too.

Glad you're enjoying the keyboard. I've never used one but looking on the web they do sound very good. (For some reason I've never really liked having the cursor keys only on the numeric pad myself, even though I virtually never use the numeric pad at all for numbers or cursor keys and so in theory it shouldn't bother me at all. But I haven't seen a keyboard of that style in decades, so maybe I'd feel differently these days anyway.)

**Comment by SteveFosdick** [comment] 2020-08-07 21:50
I have fixed the transient LEDs.

I also had one last idea - you mentioned about a better choice of colour - I have made it possible to configure the colour of the LEDs separately in the config file.  This is a bit quirky, I suppose, but back in the day I modified by BBC B to have different colour LEDs.  I kept red for the shift lock as I didn't usually want to have that one on and thus the red was a warning.  At the time green LEDs were not as bright as their red counterparts so I put in a green LED in for caps lock which is on most of the time and a yellow one for the cassette motor.  That also meant I could see which LED was on even in the dark.  The master I have now is boring with them all red again.

Also, I have seen hard discs with green LEDs,  If none of the config keys are present, the default is red and one can also configure a global default with the key 'default' and then override this for specific cases so, for example, this uses a slightly darker red than the default, and makes the changes to match by BITD BBC B:
```
[leds]
default=#d4153b
cass=#d4ce15
capslk=#15d42f
```
Colours can also be specified as a tripplet:
```
default=212,21,59
```

Finally, following on from the discussion on redrawing during pause I have merged LEDs into master.  I'll keep this open just in case for a few more days.

**Comment by ZornsLemma** [comment] 2020-08-08 00:03
The configurable colour seems like a good idea to me. I don't particularly want this myself, but I have to ask because I'm sure someone else will - should the background colour and the font colour be configurable as well? (A quick look at the commit suggests they're not, apologies if I'm wrong about this.) But this could always be put in a future version if someone who wants it actually asks, of course.

It also looks like there's still an SFTODO comment in the code about maybe changing the LED colour. Perhaps worth a quick grep over master for any SFTODO comments and deleting them all, unless they point out grave as-yet-unfixed problems (which I doubt at this stage).

**Comment by ZornsLemma** [comment] 2020-08-08 00:19
PS Thanks for merging this to master. It's as much your work as mine by this stage (if not more), but it's still nice to see something I started make it all the way there!

**Comment by SteveFosdick** [comment] 2020-08-08 13:40
I have to say this all rather reminds me of the GNOME vs. KDE argument a few years ago.

The GNOME side made that case that lots of options are not needed and that, rather than be able to configure every aspect of an application or desktop's behaviour, what users really need is for the behaviour to have been well-researched and thus already optimal with no need to change it.

The KDE counter-argument is, of course, optimal for whom?  Can one set of behaviour be simultaneously optimal for new users and power users?  Maybe some things can and some can't.

So am I taking the easy way when there is a TODO saying "should we make that a more subdued colour" by making it a user option.  Personally I can't see why we can't have the best of both worlds.  The defaults should be good ones, especially those with no UI to change them as most people will run with those, but will not necessarily be right for everyone.

So philosophy aside, it makes sense to include the background colour in the configuration options and I'll review the TODOs.

**Comment by SteveFosdick** [comment] 2020-08-08 14:10
Ok, so looking in more detail the background colour that is actually visible is the colour of the box for each LED onto which the actual LED is drawn so that was one the I put in the config file.  That also implies keeping the boxes.  We could make that configurable too.

The onlt TODO left is the The linux-gui.c file and that does not need to be maintained - this was for the Allegro 4 version.

**Comment by SteveFosdick** [comment] 2021-03-07 20:10
I think this is now complete.

**Closed as completed by SteveFosdick** 2021-03-07 20:10 UTC
Labels: enhancement
